services:
  - type: web
    name: mbti-render
    env: node
    buildCommand: |
      npm install
      npm run setup-static
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: DB_NAME
        value: html-snippet-builder
      - key: REACT_APP_API_URL
        value: https://mbti-render.onrender.com
      - key: REACT_APP_SOCKET_URL
        value: https://mbti-render.onrender.com
    healthCheckPath: /api/health
    autoDeploy: true 