services:
  - type: web
    name: mbti-render
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MISTRAL_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: DB_NAME
        value: html-snippet-builder
    healthCheckPath: /api/health
    autoDeploy: true 